env:
  TERM: xterm-256color
window:
  position:
    x: 0
    y: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  decorations: full
  title: Alacritty
  dynamic_title: true
scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: monospace
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  bold_italic:
    family: monospace
    style: Bold Italic
  size: 12
  offset:
    x: 0
    y: 0
colors:
  primary:
    background: "#1a1a1a"
    foreground: "#c4c5b5"
  normal:
    black: "#1a1a1a"
    red: "#f4005f"
    green: "#98e024"
    yellow: "#fa8419"
    blue: "#9d65ff"
    magenta: "#f4005f"
    cyan: "#58d1eb"
    white: "#c4c5b5"
  bright:
    black: "#625e4c"
    red: "#f4005f"
    green: "#98e024"
    yellow: "#e0d561"
    blue: "#9d65ff"
    magenta: "#f4005f"
    cyan: "#58d1eb"
    white: "#f6f6ef"
bell:
  animation: EaseOutExpo
  duration: 0
  color: "#ffffff"
live_config_reload: true
shell:
  program: /usr/bin/fish
  args:
    - --login
    - -c
    - "tmux a -t base  || tmux new -s base"
  persistent_logging: false
  log_level: Warn
  print_events: false
