env:
  TERM: alacritty
  startup_mode: Windowed
  title: Alacritty
scrolling:
  history: 10000
font:
  normal:
    Default:
      - (macOS) Menlo
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
  bold_italic:
    family: Menlo
    style: Bold Italic
  size: 13.5
draw_bold_text_with_bright_colors: true
colors:
  name: Monokai (dark)
  author: Chris Kempson
  primary:
    background: "#272822"
    foreground: "#f8f8f2"
  cursor:
    text: "#272822"
    cursor: "#f8f8f2"
  normal:
    black: "#272822"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f8f8f2"
  bright:
    black: "#75715e"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f9f8f5"
shell:
  program: /usr/local/bin/fish
  args:
    - -l
    - -c
    - tmux a -t base || tmux new -s base
key_bindings:
  - key: Paste
    action: Paste
  - key: Copy
    action: Copy
  - key: L
    mods: Control
    action: ClearLogNotice
  - key: L
    mods: Control
    mode: ~Vi|~Search
    chars: "\f"
  - key: PageUp
    mods: Shift
    mode: ~Alt
    action: ScrollPageUp
  - key: PageDown
    mods: Shift
    mode: ~Alt
    action: ScrollPageDown
  - key: Home
    mods: Shift
    mode: ~Alt
    action: ScrollToTop
  - key: End
    mods: Shift
    mode: ~Alt
    action: ScrollToBottom
  - key: Return
    mode: Search|Vi
    action: SearchConfirm
  - key: Escape
    mode: Search
    action: SearchCancel
  - key: C
    mods: Control
    mode: Search
    action: SearchCancel
  - key: U
    mods: Control
    mode: Search
    action: SearchClear
  - key: W
    mods: Control
    mode: Search
    action: SearchDeleteWord
  - key: P
    mods: Control
    mode: Search
    action: SearchHistoryPrevious
  - key: N
    mods: Control
    mode: Search
    action: SearchHistoryNext
  - key: Up
    mode: Search
    action: SearchHistoryPrevious
  - key: Down
    mode: Search
    action: SearchHistoryNext
  - key: Return
    mode: Search|~Vi
    action: SearchFocusNext
  - key: Return
    mods: Shift
    mode: Search|~Vi
    action: SearchFocusPrevious
  - key: K
    mods: Command
    mode: ~Vi|~Search
    chars: "\f"
  - key: K
    mods: Command
    mode: ~Vi|~Search
    action: ClearHistory
  - key: Key0
    mods: Command
    action: ResetFontSize
  - key: Equals
    mods: Command
    action: IncreaseFontSize
  - key: Plus
    mods: Command
    action: IncreaseFontSize
  - key: NumpadAdd
    mods: Command
    action: IncreaseFontSize
  - key: Minus
    mods: Command
    action: DecreaseFontSize
  - key: NumpadSubtract
    mods: Command
    action: DecreaseFontSize
  - key: V
    mods: Command
    action: Paste
  - key: C
    mods: Command
    action: Copy
  - key: C
    mods: Command
    mode: Vi|~Search
    action: ClearSelection
  - key: H
    mods: Command
    action: Hide
  - key: H
    mods: Command|Alt
    action: HideOtherApplications
  - key: M
    mods: Command
    action: Minimize
  - key: Q
    mods: Command
    action: Quit
  - key: W
    mods: Command
    action: Quit
  - key: N
    mods: Command
    action: SpawnNewInstance
  - key: F
    mods: Command|Control
    action: ToggleFullscreen
  - key: F
    mods: Command
    mode: ~Search
    action: SearchForward
  - key: B
    mods: Command
    mode: ~Search
    action: SearchBackward
